# HRM Training Configuration for Sudoku-Extreme
# Optimized parameters for Sudoku puzzle solving

# Core hyperparameters (matching original HRM paper)
learning_rate: 0.0001
embedding_lr: 0.01  # Original uses 1e-2 for puzzle embeddings
weight_decay: 1.0   # High weight decay as in original
embedding_weight_decay: 0.1
batch_size: 256     # Original batch size for Sudoku
max_epochs: 20000

# Learning rate scheduling
warmup_steps: 2000
min_lr_ratio: 0.1

# AdamATan2 parameters (exact match to original)
beta1: 0.9
beta2: 0.95

# Model architecture (original HRM configuration)
d_model: 512
H_cycles: 2
L_cycles: 2
H_layers: 4
L_layers: 4
expansion: 2.0

# ACT and Q-learning (original parameters)
halt_max_steps: 8   # Optimized for Sudoku (original uses 16)
halt_exploration_prob: 0.1

# Sudoku-specific data configuration
train_samples: 1000
val_samples: 200
min_difficulty: 20
data_path: "data"

# Training settings
eval_interval: 2000
save_every: 2000
checkpoint_dir: "checkpoints"

# Monitoring
project_name: "hrm-sudoku"
run_name: "sudoku-extreme-training"